### ISSUE TITLE
Find a mechanism to identify local weather information

### ISSUE THREAD

**Issue by Sripadalns** [WAnD/sunnyboy#2]

**Comment by Sripadalns** [comment]
All Natural / green energy initiatives have problem associated with nature. Example: On a dense cloudy day, the solar power generated will be less. So we need to identify the weather information and communicate with back office. I

**Comment by Sripadalns** [comment]
[wether.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e5cc27324fd600118fc539/125516c66e82c728ace21e0d46ff918e2b8791ebc3abaf51ab57f5973d047d317c5da67e7381bb7aec44235559094ead490d5810f4f1da2cb4aa2e32db025fb28c341521842f1bbeb98515be04ba28894a85b5ba834ec4ee2f68.txt)

**Comment by bhravikishore** [comment]
good idea is very bad

**Comment by Sripadalns** [comment]
![weather.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e5cc27324fd600118fc539/125516c66e82c728ace21e0d46ff919b378a86bbcda5fd53b652fa912a5265296b51fa2e2586e770ed117d595b5918ac40500a43a8f18178a1a42062c80d55b98e30063e937f03a6aa8317b500bf20834d80b6ba8e4ec8ed3937aa.jpg)
